package org.example.core.parser;

public enum ParserTokenType {
    OBJECT_START,
    OBJECT_END,
    OBJECT_PROPERTY_NAME,
    OBJECT_PROPERTY_VALUE_NUMBER,
    OBJECT_PROPERTY_VALUE_STRING,
    OBJECT_PROPERTY_VALUE_BOOLEAN,
    OBJECT_PROPERTY_VALUE_NULL,
    NAME_SEPARATOR,
    VALUE_SEPARATOR,
    ARRAY_START,
    ARRAY_END,
    ARRAY_VALUE_NUMBER,
    ARRAY_VALUE_STRING,
    ARRAY_VALUE_BOOLEAN,
    ARRAY_VALUE_NULL,
    NUMBER,
    STRING,
    BOOLEAN,
    NULL
}
